//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace GeneratorDanovehoPriznani.DPH3 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Pisemnost {
        
        private PisemnostDPHDP3 dPHDP3Field;
        
        private PisemnostKontrola kontrolaField;
        
        private string verzeSWField;
        
        private string nazevSWField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHDP3 DPHDP3 {
            get {
                return this.dPHDP3Field;
            }
            set {
                this.dPHDP3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostKontrola Kontrola {
            get {
                return this.kontrolaField;
            }
            set {
                this.kontrolaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string verzeSW {
            get {
                return this.verzeSWField;
            }
            set {
                this.verzeSWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nazevSW {
            get {
                return this.nazevSWField;
            }
            set {
                this.nazevSWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHDP3 {
        
        private PisemnostDPHDP3VetaD vetaDField;
        
        private PisemnostDPHDP3VetaP vetaPField;
        
        private PisemnostDPHDP3Veta1 veta1Field;
        
        private PisemnostDPHDP3Veta2 veta2Field;
        
        private PisemnostDPHDP3Veta3 veta3Field;
        
        private PisemnostDPHDP3Veta4 veta4Field;
        
        private PisemnostDPHDP3Veta5 veta5Field;
        
        private PisemnostDPHDP3Veta6 veta6Field;
        
        private PisemnostDPHDP3VetaR[] vetaRField;
        
        private PisemnostDPHDP3ObecnaPriloha[] prilohyField;
        
        private string verzePisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHDP3VetaD VetaD {
            get {
                return this.vetaDField;
            }
            set {
                this.vetaDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHDP3VetaP VetaP {
            get {
                return this.vetaPField;
            }
            set {
                this.vetaPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHDP3Veta1 Veta1 {
            get {
                return this.veta1Field;
            }
            set {
                this.veta1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHDP3Veta2 Veta2 {
            get {
                return this.veta2Field;
            }
            set {
                this.veta2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHDP3Veta3 Veta3 {
            get {
                return this.veta3Field;
            }
            set {
                this.veta3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHDP3Veta4 Veta4 {
            get {
                return this.veta4Field;
            }
            set {
                this.veta4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHDP3Veta5 Veta5 {
            get {
                return this.veta5Field;
            }
            set {
                this.veta5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHDP3Veta6 Veta6 {
            get {
                return this.veta6Field;
            }
            set {
                this.veta6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VetaR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHDP3VetaR[] VetaR {
            get {
                return this.vetaRField;
            }
            set {
                this.vetaRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ObecnaPriloha", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PisemnostDPHDP3ObecnaPriloha[] Prilohy {
            get {
                return this.prilohyField;
            }
            set {
                this.prilohyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string verzePis {
            get {
                return this.verzePisField;
            }
            set {
                this.verzePisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHDP3VetaD {
        
        private decimal c_okecField;
        
        private bool c_okecFieldSpecified;
        
        private decimal ctvrtField;
        
        private bool ctvrtFieldSpecified;
        
        private string d_poddpField;
        
        private string d_zjistField;
        
        private string dapdph_formaField;
        
        private string dokumentField;
        
        private string k_uladisField;
        
        private string kod_zoField;
        
        private decimal mesicField;
        
        private bool mesicFieldSpecified;
        
        private decimal rokField;
        
        private string transField;
        
        private string typ_platceField;
        
        private string zdobd_doField;
        
        private string zdobd_odField;
        
        public PisemnostDPHDP3VetaD() {
            this.dokumentField = "DP3";
            this.k_uladisField = "DPH";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_okec {
            get {
                return this.c_okecField;
            }
            set {
                this.c_okecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c_okecSpecified {
            get {
                return this.c_okecFieldSpecified;
            }
            set {
                this.c_okecFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ctvrt {
            get {
                return this.ctvrtField;
            }
            set {
                this.ctvrtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ctvrtSpecified {
            get {
                return this.ctvrtFieldSpecified;
            }
            set {
                this.ctvrtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string d_poddp {
            get {
                return this.d_poddpField;
            }
            set {
                this.d_poddpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string d_zjist {
            get {
                return this.d_zjistField;
            }
            set {
                this.d_zjistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dapdph_forma {
            get {
                return this.dapdph_formaField;
            }
            set {
                this.dapdph_formaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string k_uladis {
            get {
                return this.k_uladisField;
            }
            set {
                this.k_uladisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kod_zo {
            get {
                return this.kod_zoField;
            }
            set {
                this.kod_zoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal mesic {
            get {
                return this.mesicField;
            }
            set {
                this.mesicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mesicSpecified {
            get {
                return this.mesicFieldSpecified;
            }
            set {
                this.mesicFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal rok {
            get {
                return this.rokField;
            }
            set {
                this.rokField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trans {
            get {
                return this.transField;
            }
            set {
                this.transField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typ_platce {
            get {
                return this.typ_platceField;
            }
            set {
                this.typ_platceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zdobd_do {
            get {
                return this.zdobd_doField;
            }
            set {
                this.zdobd_doField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zdobd_od {
            get {
                return this.zdobd_odField;
            }
            set {
                this.zdobd_odField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHDP3VetaP {
        
        private string c_orientField;
        
        private decimal c_popField;
        
        private bool c_popFieldSpecified;
        
        private string c_telefField;
        
        private decimal c_ufoField;
        
        private decimal c_pracufoField;
        
        private bool c_pracufoFieldSpecified;
        
        private string dicField;
        
        private string emailField;
        
        private string jmenoField;
        
        private string naz_obceField;
        
        private string opr_jmenoField;
        
        private string opr_postaveniField;
        
        private string opr_prijmeniField;
        
        private string prijmeniField;
        
        private string pscField;
        
        private string sest_jmenoField;
        
        private string sest_prijmeniField;
        
        private string sest_telefField;
        
        private string statField;
        
        private string titulField;
        
        private string typ_dsField;
        
        private string uliceField;
        
        private string zast_dat_narField;
        
        private string zast_ev_cisloField;
        
        private string zast_icField;
        
        private string zast_jmenoField;
        
        private string zast_kodField;
        
        private string zast_nazevField;
        
        private string zast_prijmeniField;
        
        private string zast_typField;
        
        private string zkrobchjmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c_orient {
            get {
                return this.c_orientField;
            }
            set {
                this.c_orientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_pop {
            get {
                return this.c_popField;
            }
            set {
                this.c_popField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c_popSpecified {
            get {
                return this.c_popFieldSpecified;
            }
            set {
                this.c_popFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c_telef {
            get {
                return this.c_telefField;
            }
            set {
                this.c_telefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_ufo {
            get {
                return this.c_ufoField;
            }
            set {
                this.c_ufoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_pracufo {
            get {
                return this.c_pracufoField;
            }
            set {
                this.c_pracufoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c_pracufoSpecified {
            get {
                return this.c_pracufoFieldSpecified;
            }
            set {
                this.c_pracufoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dic {
            get {
                return this.dicField;
            }
            set {
                this.dicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string jmeno {
            get {
                return this.jmenoField;
            }
            set {
                this.jmenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string naz_obce {
            get {
                return this.naz_obceField;
            }
            set {
                this.naz_obceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string opr_jmeno {
            get {
                return this.opr_jmenoField;
            }
            set {
                this.opr_jmenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string opr_postaveni {
            get {
                return this.opr_postaveniField;
            }
            set {
                this.opr_postaveniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string opr_prijmeni {
            get {
                return this.opr_prijmeniField;
            }
            set {
                this.opr_prijmeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string prijmeni {
            get {
                return this.prijmeniField;
            }
            set {
                this.prijmeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string psc {
            get {
                return this.pscField;
            }
            set {
                this.pscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sest_jmeno {
            get {
                return this.sest_jmenoField;
            }
            set {
                this.sest_jmenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sest_prijmeni {
            get {
                return this.sest_prijmeniField;
            }
            set {
                this.sest_prijmeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sest_telef {
            get {
                return this.sest_telefField;
            }
            set {
                this.sest_telefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string titul {
            get {
                return this.titulField;
            }
            set {
                this.titulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typ_ds {
            get {
                return this.typ_dsField;
            }
            set {
                this.typ_dsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ulice {
            get {
                return this.uliceField;
            }
            set {
                this.uliceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_dat_nar {
            get {
                return this.zast_dat_narField;
            }
            set {
                this.zast_dat_narField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_ev_cislo {
            get {
                return this.zast_ev_cisloField;
            }
            set {
                this.zast_ev_cisloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_ic {
            get {
                return this.zast_icField;
            }
            set {
                this.zast_icField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_jmeno {
            get {
                return this.zast_jmenoField;
            }
            set {
                this.zast_jmenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_kod {
            get {
                return this.zast_kodField;
            }
            set {
                this.zast_kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_nazev {
            get {
                return this.zast_nazevField;
            }
            set {
                this.zast_nazevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_prijmeni {
            get {
                return this.zast_prijmeniField;
            }
            set {
                this.zast_prijmeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_typ {
            get {
                return this.zast_typField;
            }
            set {
                this.zast_typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zkrobchjm {
            get {
                return this.zkrobchjmField;
            }
            set {
                this.zkrobchjmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHDP3Veta1 {
        
        private decimal dan23Field;
        
        private bool dan23FieldSpecified;
        
        private decimal dan5Field;
        
        private bool dan5FieldSpecified;
        
        private decimal dan_dzb23Field;
        
        private bool dan_dzb23FieldSpecified;
        
        private decimal dan_dzb5Field;
        
        private bool dan_dzb5FieldSpecified;
        
        private decimal dan_pdop_nrgField;
        
        private bool dan_pdop_nrgFieldSpecified;
        
        private decimal dan_psl23_eField;
        
        private bool dan_psl23_eFieldSpecified;
        
        private decimal dan_psl23_zField;
        
        private bool dan_psl23_zFieldSpecified;
        
        private decimal dan_psl5_eField;
        
        private bool dan_psl5_eFieldSpecified;
        
        private decimal dan_psl5_zField;
        
        private bool dan_psl5_zFieldSpecified;
        
        private decimal dan_pzb23Field;
        
        private bool dan_pzb23FieldSpecified;
        
        private decimal dan_pzb5Field;
        
        private bool dan_pzb5FieldSpecified;
        
        private decimal dan_rpren23Field;
        
        private bool dan_rpren23FieldSpecified;
        
        private decimal dan_rpren5Field;
        
        private bool dan_rpren5FieldSpecified;
        
        private decimal dov_zb23Field;
        
        private bool dov_zb23FieldSpecified;
        
        private decimal dov_zb5Field;
        
        private bool dov_zb5FieldSpecified;
        
        private decimal obrat23Field;
        
        private bool obrat23FieldSpecified;
        
        private decimal obrat5Field;
        
        private bool obrat5FieldSpecified;
        
        private decimal p_dop_nrgField;
        
        private bool p_dop_nrgFieldSpecified;
        
        private decimal p_sl23_eField;
        
        private bool p_sl23_eFieldSpecified;
        
        private decimal p_sl23_zField;
        
        private bool p_sl23_zFieldSpecified;
        
        private decimal p_sl5_eField;
        
        private bool p_sl5_eFieldSpecified;
        
        private decimal p_sl5_zField;
        
        private bool p_sl5_zFieldSpecified;
        
        private decimal p_zb23Field;
        
        private bool p_zb23FieldSpecified;
        
        private decimal p_zb5Field;
        
        private bool p_zb5FieldSpecified;
        
        private decimal rez_pren23Field;
        
        private bool rez_pren23FieldSpecified;
        
        private decimal rez_pren5Field;
        
        private bool rez_pren5FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan23 {
            get {
                return this.dan23Field;
            }
            set {
                this.dan23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan23Specified {
            get {
                return this.dan23FieldSpecified;
            }
            set {
                this.dan23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan5 {
            get {
                return this.dan5Field;
            }
            set {
                this.dan5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan5Specified {
            get {
                return this.dan5FieldSpecified;
            }
            set {
                this.dan5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_dzb23 {
            get {
                return this.dan_dzb23Field;
            }
            set {
                this.dan_dzb23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_dzb23Specified {
            get {
                return this.dan_dzb23FieldSpecified;
            }
            set {
                this.dan_dzb23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_dzb5 {
            get {
                return this.dan_dzb5Field;
            }
            set {
                this.dan_dzb5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_dzb5Specified {
            get {
                return this.dan_dzb5FieldSpecified;
            }
            set {
                this.dan_dzb5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_pdop_nrg {
            get {
                return this.dan_pdop_nrgField;
            }
            set {
                this.dan_pdop_nrgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_pdop_nrgSpecified {
            get {
                return this.dan_pdop_nrgFieldSpecified;
            }
            set {
                this.dan_pdop_nrgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_psl23_e {
            get {
                return this.dan_psl23_eField;
            }
            set {
                this.dan_psl23_eField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_psl23_eSpecified {
            get {
                return this.dan_psl23_eFieldSpecified;
            }
            set {
                this.dan_psl23_eFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_psl23_z {
            get {
                return this.dan_psl23_zField;
            }
            set {
                this.dan_psl23_zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_psl23_zSpecified {
            get {
                return this.dan_psl23_zFieldSpecified;
            }
            set {
                this.dan_psl23_zFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_psl5_e {
            get {
                return this.dan_psl5_eField;
            }
            set {
                this.dan_psl5_eField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_psl5_eSpecified {
            get {
                return this.dan_psl5_eFieldSpecified;
            }
            set {
                this.dan_psl5_eFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_psl5_z {
            get {
                return this.dan_psl5_zField;
            }
            set {
                this.dan_psl5_zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_psl5_zSpecified {
            get {
                return this.dan_psl5_zFieldSpecified;
            }
            set {
                this.dan_psl5_zFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_pzb23 {
            get {
                return this.dan_pzb23Field;
            }
            set {
                this.dan_pzb23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_pzb23Specified {
            get {
                return this.dan_pzb23FieldSpecified;
            }
            set {
                this.dan_pzb23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_pzb5 {
            get {
                return this.dan_pzb5Field;
            }
            set {
                this.dan_pzb5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_pzb5Specified {
            get {
                return this.dan_pzb5FieldSpecified;
            }
            set {
                this.dan_pzb5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_rpren23 {
            get {
                return this.dan_rpren23Field;
            }
            set {
                this.dan_rpren23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_rpren23Specified {
            get {
                return this.dan_rpren23FieldSpecified;
            }
            set {
                this.dan_rpren23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_rpren5 {
            get {
                return this.dan_rpren5Field;
            }
            set {
                this.dan_rpren5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_rpren5Specified {
            get {
                return this.dan_rpren5FieldSpecified;
            }
            set {
                this.dan_rpren5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dov_zb23 {
            get {
                return this.dov_zb23Field;
            }
            set {
                this.dov_zb23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dov_zb23Specified {
            get {
                return this.dov_zb23FieldSpecified;
            }
            set {
                this.dov_zb23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dov_zb5 {
            get {
                return this.dov_zb5Field;
            }
            set {
                this.dov_zb5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dov_zb5Specified {
            get {
                return this.dov_zb5FieldSpecified;
            }
            set {
                this.dov_zb5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal obrat23 {
            get {
                return this.obrat23Field;
            }
            set {
                this.obrat23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool obrat23Specified {
            get {
                return this.obrat23FieldSpecified;
            }
            set {
                this.obrat23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal obrat5 {
            get {
                return this.obrat5Field;
            }
            set {
                this.obrat5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool obrat5Specified {
            get {
                return this.obrat5FieldSpecified;
            }
            set {
                this.obrat5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal p_dop_nrg {
            get {
                return this.p_dop_nrgField;
            }
            set {
                this.p_dop_nrgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool p_dop_nrgSpecified {
            get {
                return this.p_dop_nrgFieldSpecified;
            }
            set {
                this.p_dop_nrgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal p_sl23_e {
            get {
                return this.p_sl23_eField;
            }
            set {
                this.p_sl23_eField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool p_sl23_eSpecified {
            get {
                return this.p_sl23_eFieldSpecified;
            }
            set {
                this.p_sl23_eFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal p_sl23_z {
            get {
                return this.p_sl23_zField;
            }
            set {
                this.p_sl23_zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool p_sl23_zSpecified {
            get {
                return this.p_sl23_zFieldSpecified;
            }
            set {
                this.p_sl23_zFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal p_sl5_e {
            get {
                return this.p_sl5_eField;
            }
            set {
                this.p_sl5_eField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool p_sl5_eSpecified {
            get {
                return this.p_sl5_eFieldSpecified;
            }
            set {
                this.p_sl5_eFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal p_sl5_z {
            get {
                return this.p_sl5_zField;
            }
            set {
                this.p_sl5_zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool p_sl5_zSpecified {
            get {
                return this.p_sl5_zFieldSpecified;
            }
            set {
                this.p_sl5_zFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal p_zb23 {
            get {
                return this.p_zb23Field;
            }
            set {
                this.p_zb23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool p_zb23Specified {
            get {
                return this.p_zb23FieldSpecified;
            }
            set {
                this.p_zb23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal p_zb5 {
            get {
                return this.p_zb5Field;
            }
            set {
                this.p_zb5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool p_zb5Specified {
            get {
                return this.p_zb5FieldSpecified;
            }
            set {
                this.p_zb5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal rez_pren23 {
            get {
                return this.rez_pren23Field;
            }
            set {
                this.rez_pren23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rez_pren23Specified {
            get {
                return this.rez_pren23FieldSpecified;
            }
            set {
                this.rez_pren23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal rez_pren5 {
            get {
                return this.rez_pren5Field;
            }
            set {
                this.rez_pren5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rez_pren5Specified {
            get {
                return this.rez_pren5FieldSpecified;
            }
            set {
                this.rez_pren5FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHDP3Veta2 {
        
        private decimal dod_dop_nrgField;
        
        private bool dod_dop_nrgFieldSpecified;
        
        private decimal dod_zbField;
        
        private bool dod_zbFieldSpecified;
        
        private decimal pln_ostField;
        
        private bool pln_ostFieldSpecified;
        
        private decimal pln_rez_prenField;
        
        private bool pln_rez_prenFieldSpecified;
        
        private decimal pln_sluzbyField;
        
        private bool pln_sluzbyFieldSpecified;
        
        private decimal pln_vyvozField;
        
        private bool pln_vyvozFieldSpecified;
        
        private decimal pln_zaslaniField;
        
        private bool pln_zaslaniFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dod_dop_nrg {
            get {
                return this.dod_dop_nrgField;
            }
            set {
                this.dod_dop_nrgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dod_dop_nrgSpecified {
            get {
                return this.dod_dop_nrgFieldSpecified;
            }
            set {
                this.dod_dop_nrgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dod_zb {
            get {
                return this.dod_zbField;
            }
            set {
                this.dod_zbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dod_zbSpecified {
            get {
                return this.dod_zbFieldSpecified;
            }
            set {
                this.dod_zbFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pln_ost {
            get {
                return this.pln_ostField;
            }
            set {
                this.pln_ostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pln_ostSpecified {
            get {
                return this.pln_ostFieldSpecified;
            }
            set {
                this.pln_ostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pln_rez_pren {
            get {
                return this.pln_rez_prenField;
            }
            set {
                this.pln_rez_prenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pln_rez_prenSpecified {
            get {
                return this.pln_rez_prenFieldSpecified;
            }
            set {
                this.pln_rez_prenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pln_sluzby {
            get {
                return this.pln_sluzbyField;
            }
            set {
                this.pln_sluzbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pln_sluzbySpecified {
            get {
                return this.pln_sluzbyFieldSpecified;
            }
            set {
                this.pln_sluzbyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pln_vyvoz {
            get {
                return this.pln_vyvozField;
            }
            set {
                this.pln_vyvozField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pln_vyvozSpecified {
            get {
                return this.pln_vyvozFieldSpecified;
            }
            set {
                this.pln_vyvozFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pln_zaslani {
            get {
                return this.pln_zaslaniField;
            }
            set {
                this.pln_zaslaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pln_zaslaniSpecified {
            get {
                return this.pln_zaslaniFieldSpecified;
            }
            set {
                this.pln_zaslaniFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHDP3Veta3 {
        
        private decimal dov_osvField;
        
        private bool dov_osvFieldSpecified;
        
        private decimal opr_dluzField;
        
        private bool opr_dluzFieldSpecified;
        
        private decimal opr_veritField;
        
        private bool opr_veritFieldSpecified;
        
        private decimal tri_dozbField;
        
        private bool tri_dozbFieldSpecified;
        
        private decimal tri_pozbField;
        
        private bool tri_pozbFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dov_osv {
            get {
                return this.dov_osvField;
            }
            set {
                this.dov_osvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dov_osvSpecified {
            get {
                return this.dov_osvFieldSpecified;
            }
            set {
                this.dov_osvFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal opr_dluz {
            get {
                return this.opr_dluzField;
            }
            set {
                this.opr_dluzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opr_dluzSpecified {
            get {
                return this.opr_dluzFieldSpecified;
            }
            set {
                this.opr_dluzFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal opr_verit {
            get {
                return this.opr_veritField;
            }
            set {
                this.opr_veritField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opr_veritSpecified {
            get {
                return this.opr_veritFieldSpecified;
            }
            set {
                this.opr_veritFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal tri_dozb {
            get {
                return this.tri_dozbField;
            }
            set {
                this.tri_dozbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tri_dozbSpecified {
            get {
                return this.tri_dozbFieldSpecified;
            }
            set {
                this.tri_dozbFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal tri_pozb {
            get {
                return this.tri_pozbField;
            }
            set {
                this.tri_pozbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tri_pozbSpecified {
            get {
                return this.tri_pozbFieldSpecified;
            }
            set {
                this.tri_pozbFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHDP3Veta4 {
        
        private decimal dov_cuField;
        
        private bool dov_cuFieldSpecified;
        
        private decimal nar_majField;
        
        private bool nar_majFieldSpecified;
        
        private decimal nar_zdp23Field;
        
        private bool nar_zdp23FieldSpecified;
        
        private decimal nar_zdp5Field;
        
        private bool nar_zdp5FieldSpecified;
        
        private decimal od_majField;
        
        private bool od_majFieldSpecified;
        
        private decimal od_zdp23Field;
        
        private bool od_zdp23FieldSpecified;
        
        private decimal od_zdp5Field;
        
        private bool od_zdp5FieldSpecified;
        
        private decimal odkr_majField;
        
        private bool odkr_majFieldSpecified;
        
        private decimal odkr_zdp23Field;
        
        private bool odkr_zdp23FieldSpecified;
        
        private decimal odkr_zdp5Field;
        
        private bool odkr_zdp5FieldSpecified;
        
        private decimal odp_cuField;
        
        private bool odp_cuFieldSpecified;
        
        private decimal odp_cu_narField;
        
        private bool odp_cu_narFieldSpecified;
        
        private decimal odp_rez_narField;
        
        private bool odp_rez_narFieldSpecified;
        
        private decimal odp_rezimField;
        
        private bool odp_rezimFieldSpecified;
        
        private decimal odp_sum_krField;
        
        private bool odp_sum_krFieldSpecified;
        
        private decimal odp_sum_narField;
        
        private bool odp_sum_narFieldSpecified;
        
        private decimal odp_tuz23Field;
        
        private bool odp_tuz23FieldSpecified;
        
        private decimal odp_tuz23_narField;
        
        private bool odp_tuz23_narFieldSpecified;
        
        private decimal odp_tuz5Field;
        
        private bool odp_tuz5FieldSpecified;
        
        private decimal odp_tuz5_narField;
        
        private bool odp_tuz5_narFieldSpecified;
        
        private decimal pln23Field;
        
        private bool pln23FieldSpecified;
        
        private decimal pln5Field;
        
        private bool pln5FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dov_cu {
            get {
                return this.dov_cuField;
            }
            set {
                this.dov_cuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dov_cuSpecified {
            get {
                return this.dov_cuFieldSpecified;
            }
            set {
                this.dov_cuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal nar_maj {
            get {
                return this.nar_majField;
            }
            set {
                this.nar_majField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nar_majSpecified {
            get {
                return this.nar_majFieldSpecified;
            }
            set {
                this.nar_majFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal nar_zdp23 {
            get {
                return this.nar_zdp23Field;
            }
            set {
                this.nar_zdp23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nar_zdp23Specified {
            get {
                return this.nar_zdp23FieldSpecified;
            }
            set {
                this.nar_zdp23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal nar_zdp5 {
            get {
                return this.nar_zdp5Field;
            }
            set {
                this.nar_zdp5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nar_zdp5Specified {
            get {
                return this.nar_zdp5FieldSpecified;
            }
            set {
                this.nar_zdp5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal od_maj {
            get {
                return this.od_majField;
            }
            set {
                this.od_majField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool od_majSpecified {
            get {
                return this.od_majFieldSpecified;
            }
            set {
                this.od_majFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal od_zdp23 {
            get {
                return this.od_zdp23Field;
            }
            set {
                this.od_zdp23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool od_zdp23Specified {
            get {
                return this.od_zdp23FieldSpecified;
            }
            set {
                this.od_zdp23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal od_zdp5 {
            get {
                return this.od_zdp5Field;
            }
            set {
                this.od_zdp5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool od_zdp5Specified {
            get {
                return this.od_zdp5FieldSpecified;
            }
            set {
                this.od_zdp5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odkr_maj {
            get {
                return this.odkr_majField;
            }
            set {
                this.odkr_majField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odkr_majSpecified {
            get {
                return this.odkr_majFieldSpecified;
            }
            set {
                this.odkr_majFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odkr_zdp23 {
            get {
                return this.odkr_zdp23Field;
            }
            set {
                this.odkr_zdp23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odkr_zdp23Specified {
            get {
                return this.odkr_zdp23FieldSpecified;
            }
            set {
                this.odkr_zdp23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odkr_zdp5 {
            get {
                return this.odkr_zdp5Field;
            }
            set {
                this.odkr_zdp5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odkr_zdp5Specified {
            get {
                return this.odkr_zdp5FieldSpecified;
            }
            set {
                this.odkr_zdp5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_cu {
            get {
                return this.odp_cuField;
            }
            set {
                this.odp_cuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_cuSpecified {
            get {
                return this.odp_cuFieldSpecified;
            }
            set {
                this.odp_cuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_cu_nar {
            get {
                return this.odp_cu_narField;
            }
            set {
                this.odp_cu_narField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_cu_narSpecified {
            get {
                return this.odp_cu_narFieldSpecified;
            }
            set {
                this.odp_cu_narFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_rez_nar {
            get {
                return this.odp_rez_narField;
            }
            set {
                this.odp_rez_narField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_rez_narSpecified {
            get {
                return this.odp_rez_narFieldSpecified;
            }
            set {
                this.odp_rez_narFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_rezim {
            get {
                return this.odp_rezimField;
            }
            set {
                this.odp_rezimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_rezimSpecified {
            get {
                return this.odp_rezimFieldSpecified;
            }
            set {
                this.odp_rezimFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_sum_kr {
            get {
                return this.odp_sum_krField;
            }
            set {
                this.odp_sum_krField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_sum_krSpecified {
            get {
                return this.odp_sum_krFieldSpecified;
            }
            set {
                this.odp_sum_krFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_sum_nar {
            get {
                return this.odp_sum_narField;
            }
            set {
                this.odp_sum_narField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_sum_narSpecified {
            get {
                return this.odp_sum_narFieldSpecified;
            }
            set {
                this.odp_sum_narFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_tuz23 {
            get {
                return this.odp_tuz23Field;
            }
            set {
                this.odp_tuz23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_tuz23Specified {
            get {
                return this.odp_tuz23FieldSpecified;
            }
            set {
                this.odp_tuz23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_tuz23_nar {
            get {
                return this.odp_tuz23_narField;
            }
            set {
                this.odp_tuz23_narField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_tuz23_narSpecified {
            get {
                return this.odp_tuz23_narFieldSpecified;
            }
            set {
                this.odp_tuz23_narFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_tuz5 {
            get {
                return this.odp_tuz5Field;
            }
            set {
                this.odp_tuz5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_tuz5Specified {
            get {
                return this.odp_tuz5FieldSpecified;
            }
            set {
                this.odp_tuz5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_tuz5_nar {
            get {
                return this.odp_tuz5_narField;
            }
            set {
                this.odp_tuz5_narField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_tuz5_narSpecified {
            get {
                return this.odp_tuz5_narFieldSpecified;
            }
            set {
                this.odp_tuz5_narFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pln23 {
            get {
                return this.pln23Field;
            }
            set {
                this.pln23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pln23Specified {
            get {
                return this.pln23FieldSpecified;
            }
            set {
                this.pln23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pln5 {
            get {
                return this.pln5Field;
            }
            set {
                this.pln5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pln5Specified {
            get {
                return this.pln5FieldSpecified;
            }
            set {
                this.pln5FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHDP3Veta5 {
        
        private decimal koef_p20_novField;
        
        private bool koef_p20_novFieldSpecified;
        
        private decimal koef_p20_vyporField;
        
        private bool koef_p20_vyporFieldSpecified;
        
        private decimal odp_uprav_kfField;
        
        private bool odp_uprav_kfFieldSpecified;
        
        private decimal pln_nkfField;
        
        private bool pln_nkfFieldSpecified;
        
        private decimal plnosv_kfField;
        
        private bool plnosv_kfFieldSpecified;
        
        private decimal plnosv_nkfField;
        
        private bool plnosv_nkfFieldSpecified;
        
        private decimal vypor_odpField;
        
        private bool vypor_odpFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal koef_p20_nov {
            get {
                return this.koef_p20_novField;
            }
            set {
                this.koef_p20_novField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool koef_p20_novSpecified {
            get {
                return this.koef_p20_novFieldSpecified;
            }
            set {
                this.koef_p20_novFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal koef_p20_vypor {
            get {
                return this.koef_p20_vyporField;
            }
            set {
                this.koef_p20_vyporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool koef_p20_vyporSpecified {
            get {
                return this.koef_p20_vyporFieldSpecified;
            }
            set {
                this.koef_p20_vyporFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_uprav_kf {
            get {
                return this.odp_uprav_kfField;
            }
            set {
                this.odp_uprav_kfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_uprav_kfSpecified {
            get {
                return this.odp_uprav_kfFieldSpecified;
            }
            set {
                this.odp_uprav_kfFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pln_nkf {
            get {
                return this.pln_nkfField;
            }
            set {
                this.pln_nkfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pln_nkfSpecified {
            get {
                return this.pln_nkfFieldSpecified;
            }
            set {
                this.pln_nkfFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal plnosv_kf {
            get {
                return this.plnosv_kfField;
            }
            set {
                this.plnosv_kfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plnosv_kfSpecified {
            get {
                return this.plnosv_kfFieldSpecified;
            }
            set {
                this.plnosv_kfFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal plnosv_nkf {
            get {
                return this.plnosv_nkfField;
            }
            set {
                this.plnosv_nkfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plnosv_nkfSpecified {
            get {
                return this.plnosv_nkfFieldSpecified;
            }
            set {
                this.plnosv_nkfFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal vypor_odp {
            get {
                return this.vypor_odpField;
            }
            set {
                this.vypor_odpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vypor_odpSpecified {
            get {
                return this.vypor_odpFieldSpecified;
            }
            set {
                this.vypor_odpFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHDP3Veta6 {
        
        private decimal dan_vracField;
        
        private bool dan_vracFieldSpecified;
        
        private decimal dan_zocelkField;
        
        private bool dan_zocelkFieldSpecified;
        
        private decimal danoField;
        
        private bool danoFieldSpecified;
        
        private decimal dano_daField;
        
        private bool dano_daFieldSpecified;
        
        private decimal dano_noField;
        
        private bool dano_noFieldSpecified;
        
        private decimal odp_zocelkField;
        
        private bool odp_zocelkFieldSpecified;
        
        private decimal uprav_odpField;
        
        private bool uprav_odpFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_vrac {
            get {
                return this.dan_vracField;
            }
            set {
                this.dan_vracField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_vracSpecified {
            get {
                return this.dan_vracFieldSpecified;
            }
            set {
                this.dan_vracFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan_zocelk {
            get {
                return this.dan_zocelkField;
            }
            set {
                this.dan_zocelkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan_zocelkSpecified {
            get {
                return this.dan_zocelkFieldSpecified;
            }
            set {
                this.dan_zocelkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dano {
            get {
                return this.danoField;
            }
            set {
                this.danoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool danoSpecified {
            get {
                return this.danoFieldSpecified;
            }
            set {
                this.danoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dano_da {
            get {
                return this.dano_daField;
            }
            set {
                this.dano_daField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dano_daSpecified {
            get {
                return this.dano_daFieldSpecified;
            }
            set {
                this.dano_daFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dano_no {
            get {
                return this.dano_noField;
            }
            set {
                this.dano_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dano_noSpecified {
            get {
                return this.dano_noFieldSpecified;
            }
            set {
                this.dano_noFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal odp_zocelk {
            get {
                return this.odp_zocelkField;
            }
            set {
                this.odp_zocelkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odp_zocelkSpecified {
            get {
                return this.odp_zocelkFieldSpecified;
            }
            set {
                this.odp_zocelkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal uprav_odp {
            get {
                return this.uprav_odpField;
            }
            set {
                this.uprav_odpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uprav_odpSpecified {
            get {
                return this.uprav_odpFieldSpecified;
            }
            set {
                this.uprav_odpFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHDP3VetaR {
        
        private decimal poradiField;
        
        private string t_prilohyField;
        
        private string kod_sekceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal poradi {
            get {
                return this.poradiField;
            }
            set {
                this.poradiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string t_prilohy {
            get {
                return this.t_prilohyField;
            }
            set {
                this.t_prilohyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kod_sekce {
            get {
                return this.kod_sekceField;
            }
            set {
                this.kod_sekceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHDP3ObecnaPriloha {
        
        private decimal cisloField;
        
        private string nazevField;
        
        private string jm_souboruField;
        
        private PisemnostDPHDP3ObecnaPrilohaKodovani kodovaniField;
        
        private bool kodovaniFieldSpecified;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal cislo {
            get {
                return this.cisloField;
            }
            set {
                this.cisloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nazev {
            get {
                return this.nazevField;
            }
            set {
                this.nazevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string jm_souboru {
            get {
                return this.jm_souboruField;
            }
            set {
                this.jm_souboruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PisemnostDPHDP3ObecnaPrilohaKodovani kodovani {
            get {
                return this.kodovaniField;
            }
            set {
                this.kodovaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kodovaniSpecified {
            get {
                return this.kodovaniFieldSpecified;
            }
            set {
                this.kodovaniFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum PisemnostDPHDP3ObecnaPrilohaKodovani {
        
        /// <remarks/>
        base64,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostKontrola {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
}
