//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace GeneratorDanovehoPriznani.KH1 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Pisemnost {
        
        private PisemnostDPHKH1 dPHKH1Field;
        
        private PisemnostKontrola kontrolaField;
        
        private string verzeSWField;
        
        private string nazevSWField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1 DPHKH1 {
            get {
                return this.dPHKH1Field;
            }
            set {
                this.dPHKH1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostKontrola Kontrola {
            get {
                return this.kontrolaField;
            }
            set {
                this.kontrolaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string verzeSW {
            get {
                return this.verzeSWField;
            }
            set {
                this.verzeSWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nazevSW {
            get {
                return this.nazevSWField;
            }
            set {
                this.nazevSWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1 {
        
        private PisemnostDPHKH1VetaD vetaDField;
        
        private PisemnostDPHKH1VetaP vetaPField;
        
        private PisemnostDPHKH1VetaA1[] vetaA1Field;
        
        private PisemnostDPHKH1VetaA2[] vetaA2Field;
        
        private PisemnostDPHKH1VetaA3[] vetaA3Field;
        
        private PisemnostDPHKH1VetaA4[] vetaA4Field;
        
        private PisemnostDPHKH1VetaA5 vetaA5Field;
        
        private PisemnostDPHKH1VetaB1[] vetaB1Field;
        
        private PisemnostDPHKH1VetaB2[] vetaB2Field;
        
        private PisemnostDPHKH1VetaB3 vetaB3Field;
        
        private PisemnostDPHKH1VetaC vetaCField;
        
        private string verzePisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1VetaD VetaD {
            get {
                return this.vetaDField;
            }
            set {
                this.vetaDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1VetaP VetaP {
            get {
                return this.vetaPField;
            }
            set {
                this.vetaPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VetaA1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1VetaA1[] VetaA1 {
            get {
                return this.vetaA1Field;
            }
            set {
                this.vetaA1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VetaA2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1VetaA2[] VetaA2 {
            get {
                return this.vetaA2Field;
            }
            set {
                this.vetaA2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VetaA3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1VetaA3[] VetaA3 {
            get {
                return this.vetaA3Field;
            }
            set {
                this.vetaA3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VetaA4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1VetaA4[] VetaA4 {
            get {
                return this.vetaA4Field;
            }
            set {
                this.vetaA4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1VetaA5 VetaA5 {
            get {
                return this.vetaA5Field;
            }
            set {
                this.vetaA5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VetaB1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1VetaB1[] VetaB1 {
            get {
                return this.vetaB1Field;
            }
            set {
                this.vetaB1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VetaB2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1VetaB2[] VetaB2 {
            get {
                return this.vetaB2Field;
            }
            set {
                this.vetaB2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1VetaB3 VetaB3 {
            get {
                return this.vetaB3Field;
            }
            set {
                this.vetaB3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PisemnostDPHKH1VetaC VetaC {
            get {
                return this.vetaCField;
            }
            set {
                this.vetaCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string verzePis {
            get {
                return this.verzePisField;
            }
            set {
                this.verzePisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1VetaD {
        
        private string dokumentField;
        
        private string k_uladisField;
        
        private decimal mesicField;
        
        private bool mesicFieldSpecified;
        
        private decimal rokField;
        
        private decimal ctvrtField;
        
        private bool ctvrtFieldSpecified;
        
        private string zdobd_odField;
        
        private string zdobd_doField;
        
        private string d_poddpField;
        
        private string khdph_formaField;
        
        private string d_zjistField;
        
        private string c_jed_vyzvyField;
        
        private string vyzva_odpField;
        
        public PisemnostDPHKH1VetaD() {
            this.dokumentField = "KH1";
            this.k_uladisField = "DPH";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string k_uladis {
            get {
                return this.k_uladisField;
            }
            set {
                this.k_uladisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal mesic {
            get {
                return this.mesicField;
            }
            set {
                this.mesicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mesicSpecified {
            get {
                return this.mesicFieldSpecified;
            }
            set {
                this.mesicFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal rok {
            get {
                return this.rokField;
            }
            set {
                this.rokField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ctvrt {
            get {
                return this.ctvrtField;
            }
            set {
                this.ctvrtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ctvrtSpecified {
            get {
                return this.ctvrtFieldSpecified;
            }
            set {
                this.ctvrtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zdobd_od {
            get {
                return this.zdobd_odField;
            }
            set {
                this.zdobd_odField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zdobd_do {
            get {
                return this.zdobd_doField;
            }
            set {
                this.zdobd_doField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string d_poddp {
            get {
                return this.d_poddpField;
            }
            set {
                this.d_poddpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string khdph_forma {
            get {
                return this.khdph_formaField;
            }
            set {
                this.khdph_formaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string d_zjist {
            get {
                return this.d_zjistField;
            }
            set {
                this.d_zjistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c_jed_vyzvy {
            get {
                return this.c_jed_vyzvyField;
            }
            set {
                this.c_jed_vyzvyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vyzva_odp {
            get {
                return this.vyzva_odpField;
            }
            set {
                this.vyzva_odpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1VetaP {
        
        private decimal c_ufoField;
        
        private decimal c_pracufoField;
        
        private bool c_pracufoFieldSpecified;
        
        private string dicField;
        
        private string typ_dsField;
        
        private string titulField;
        
        private string jmenoField;
        
        private string prijmeniField;
        
        private string zkrobchjmField;
        
        private string uliceField;
        
        private string c_orientField;
        
        private decimal c_popField;
        
        private bool c_popFieldSpecified;
        
        private string naz_obceField;
        
        private string pscField;
        
        private string statField;
        
        private string emailField;
        
        private string zast_typField;
        
        private string zast_kodField;
        
        private string zast_prijmeniField;
        
        private string zast_jmenoField;
        
        private string zast_dat_narField;
        
        private string zast_ev_cisloField;
        
        private string zast_nazevField;
        
        private string zast_icField;
        
        private string opr_jmenoField;
        
        private string opr_postaveniField;
        
        private string opr_prijmeniField;
        
        private string sest_jmenoField;
        
        private string sest_prijmeniField;
        
        private string sest_telefField;
        
        private string c_telefField;
        
        private string id_datsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_ufo {
            get {
                return this.c_ufoField;
            }
            set {
                this.c_ufoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_pracufo {
            get {
                return this.c_pracufoField;
            }
            set {
                this.c_pracufoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c_pracufoSpecified {
            get {
                return this.c_pracufoFieldSpecified;
            }
            set {
                this.c_pracufoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dic {
            get {
                return this.dicField;
            }
            set {
                this.dicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typ_ds {
            get {
                return this.typ_dsField;
            }
            set {
                this.typ_dsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string titul {
            get {
                return this.titulField;
            }
            set {
                this.titulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string jmeno {
            get {
                return this.jmenoField;
            }
            set {
                this.jmenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string prijmeni {
            get {
                return this.prijmeniField;
            }
            set {
                this.prijmeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zkrobchjm {
            get {
                return this.zkrobchjmField;
            }
            set {
                this.zkrobchjmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ulice {
            get {
                return this.uliceField;
            }
            set {
                this.uliceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c_orient {
            get {
                return this.c_orientField;
            }
            set {
                this.c_orientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_pop {
            get {
                return this.c_popField;
            }
            set {
                this.c_popField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c_popSpecified {
            get {
                return this.c_popFieldSpecified;
            }
            set {
                this.c_popFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string naz_obce {
            get {
                return this.naz_obceField;
            }
            set {
                this.naz_obceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string psc {
            get {
                return this.pscField;
            }
            set {
                this.pscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_typ {
            get {
                return this.zast_typField;
            }
            set {
                this.zast_typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_kod {
            get {
                return this.zast_kodField;
            }
            set {
                this.zast_kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_prijmeni {
            get {
                return this.zast_prijmeniField;
            }
            set {
                this.zast_prijmeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_jmeno {
            get {
                return this.zast_jmenoField;
            }
            set {
                this.zast_jmenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_dat_nar {
            get {
                return this.zast_dat_narField;
            }
            set {
                this.zast_dat_narField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_ev_cislo {
            get {
                return this.zast_ev_cisloField;
            }
            set {
                this.zast_ev_cisloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_nazev {
            get {
                return this.zast_nazevField;
            }
            set {
                this.zast_nazevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zast_ic {
            get {
                return this.zast_icField;
            }
            set {
                this.zast_icField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string opr_jmeno {
            get {
                return this.opr_jmenoField;
            }
            set {
                this.opr_jmenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string opr_postaveni {
            get {
                return this.opr_postaveniField;
            }
            set {
                this.opr_postaveniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string opr_prijmeni {
            get {
                return this.opr_prijmeniField;
            }
            set {
                this.opr_prijmeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sest_jmeno {
            get {
                return this.sest_jmenoField;
            }
            set {
                this.sest_jmenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sest_prijmeni {
            get {
                return this.sest_prijmeniField;
            }
            set {
                this.sest_prijmeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sest_telef {
            get {
                return this.sest_telefField;
            }
            set {
                this.sest_telefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c_telef {
            get {
                return this.c_telefField;
            }
            set {
                this.c_telefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_dats {
            get {
                return this.id_datsField;
            }
            set {
                this.id_datsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1VetaA1 {
        
        private decimal c_radkuField;
        
        private bool c_radkuFieldSpecified;
        
        private string dic_odbField;
        
        private string c_evid_ddField;
        
        private string duzpField;
        
        private decimal zakl_dane1Field;
        
        private string kod_pred_plField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_radku {
            get {
                return this.c_radkuField;
            }
            set {
                this.c_radkuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c_radkuSpecified {
            get {
                return this.c_radkuFieldSpecified;
            }
            set {
                this.c_radkuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dic_odb {
            get {
                return this.dic_odbField;
            }
            set {
                this.dic_odbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c_evid_dd {
            get {
                return this.c_evid_ddField;
            }
            set {
                this.c_evid_ddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duzp {
            get {
                return this.duzpField;
            }
            set {
                this.duzpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane1 {
            get {
                return this.zakl_dane1Field;
            }
            set {
                this.zakl_dane1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kod_pred_pl {
            get {
                return this.kod_pred_plField;
            }
            set {
                this.kod_pred_plField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1VetaA2 {
        
        private decimal c_radkuField;
        
        private bool c_radkuFieldSpecified;
        
        private string k_statField;
        
        private string vatid_dodField;
        
        private string c_evid_ddField;
        
        private string dppdField;
        
        private decimal zakl_dane1Field;
        
        private bool zakl_dane1FieldSpecified;
        
        private decimal dan1Field;
        
        private bool dan1FieldSpecified;
        
        private decimal zakl_dane2Field;
        
        private bool zakl_dane2FieldSpecified;
        
        private decimal dan2Field;
        
        private bool dan2FieldSpecified;
        
        private decimal zakl_dane3Field;
        
        private bool zakl_dane3FieldSpecified;
        
        private decimal dan3Field;
        
        private bool dan3FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_radku {
            get {
                return this.c_radkuField;
            }
            set {
                this.c_radkuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c_radkuSpecified {
            get {
                return this.c_radkuFieldSpecified;
            }
            set {
                this.c_radkuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string k_stat {
            get {
                return this.k_statField;
            }
            set {
                this.k_statField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vatid_dod {
            get {
                return this.vatid_dodField;
            }
            set {
                this.vatid_dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c_evid_dd {
            get {
                return this.c_evid_ddField;
            }
            set {
                this.c_evid_ddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dppd {
            get {
                return this.dppdField;
            }
            set {
                this.dppdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane1 {
            get {
                return this.zakl_dane1Field;
            }
            set {
                this.zakl_dane1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane1Specified {
            get {
                return this.zakl_dane1FieldSpecified;
            }
            set {
                this.zakl_dane1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan1 {
            get {
                return this.dan1Field;
            }
            set {
                this.dan1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan1Specified {
            get {
                return this.dan1FieldSpecified;
            }
            set {
                this.dan1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane2 {
            get {
                return this.zakl_dane2Field;
            }
            set {
                this.zakl_dane2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane2Specified {
            get {
                return this.zakl_dane2FieldSpecified;
            }
            set {
                this.zakl_dane2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan2 {
            get {
                return this.dan2Field;
            }
            set {
                this.dan2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan2Specified {
            get {
                return this.dan2FieldSpecified;
            }
            set {
                this.dan2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane3 {
            get {
                return this.zakl_dane3Field;
            }
            set {
                this.zakl_dane3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane3Specified {
            get {
                return this.zakl_dane3FieldSpecified;
            }
            set {
                this.zakl_dane3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan3 {
            get {
                return this.dan3Field;
            }
            set {
                this.dan3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan3Specified {
            get {
                return this.dan3FieldSpecified;
            }
            set {
                this.dan3FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1VetaA3 {
        
        private decimal c_radkuField;
        
        private bool c_radkuFieldSpecified;
        
        private string k_statField;
        
        private string vatid_odbField;
        
        private string jm_prijm_obchField;
        
        private string d_narozeniField;
        
        private string m_pobytu_sidloField;
        
        private string c_evid_ddField;
        
        private string dupField;
        
        private decimal osv_plneniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_radku {
            get {
                return this.c_radkuField;
            }
            set {
                this.c_radkuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c_radkuSpecified {
            get {
                return this.c_radkuFieldSpecified;
            }
            set {
                this.c_radkuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string k_stat {
            get {
                return this.k_statField;
            }
            set {
                this.k_statField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vatid_odb {
            get {
                return this.vatid_odbField;
            }
            set {
                this.vatid_odbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string jm_prijm_obch {
            get {
                return this.jm_prijm_obchField;
            }
            set {
                this.jm_prijm_obchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string d_narozeni {
            get {
                return this.d_narozeniField;
            }
            set {
                this.d_narozeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string m_pobytu_sidlo {
            get {
                return this.m_pobytu_sidloField;
            }
            set {
                this.m_pobytu_sidloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c_evid_dd {
            get {
                return this.c_evid_ddField;
            }
            set {
                this.c_evid_ddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dup {
            get {
                return this.dupField;
            }
            set {
                this.dupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal osv_plneni {
            get {
                return this.osv_plneniField;
            }
            set {
                this.osv_plneniField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1VetaA4 {
        
        private decimal c_radkuField;
        
        private bool c_radkuFieldSpecified;
        
        private string dic_odbField;
        
        private string c_evid_ddField;
        
        private string dppdField;
        
        private decimal zakl_dane1Field;
        
        private bool zakl_dane1FieldSpecified;
        
        private decimal dan1Field;
        
        private bool dan1FieldSpecified;
        
        private decimal zakl_dane2Field;
        
        private bool zakl_dane2FieldSpecified;
        
        private decimal dan2Field;
        
        private bool dan2FieldSpecified;
        
        private decimal zakl_dane3Field;
        
        private bool zakl_dane3FieldSpecified;
        
        private decimal dan3Field;
        
        private bool dan3FieldSpecified;
        
        private string kod_rezim_plField;
        
        private string zdph_44Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_radku {
            get {
                return this.c_radkuField;
            }
            set {
                this.c_radkuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c_radkuSpecified {
            get {
                return this.c_radkuFieldSpecified;
            }
            set {
                this.c_radkuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dic_odb {
            get {
                return this.dic_odbField;
            }
            set {
                this.dic_odbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c_evid_dd {
            get {
                return this.c_evid_ddField;
            }
            set {
                this.c_evid_ddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dppd {
            get {
                return this.dppdField;
            }
            set {
                this.dppdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane1 {
            get {
                return this.zakl_dane1Field;
            }
            set {
                this.zakl_dane1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane1Specified {
            get {
                return this.zakl_dane1FieldSpecified;
            }
            set {
                this.zakl_dane1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan1 {
            get {
                return this.dan1Field;
            }
            set {
                this.dan1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan1Specified {
            get {
                return this.dan1FieldSpecified;
            }
            set {
                this.dan1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane2 {
            get {
                return this.zakl_dane2Field;
            }
            set {
                this.zakl_dane2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane2Specified {
            get {
                return this.zakl_dane2FieldSpecified;
            }
            set {
                this.zakl_dane2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan2 {
            get {
                return this.dan2Field;
            }
            set {
                this.dan2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan2Specified {
            get {
                return this.dan2FieldSpecified;
            }
            set {
                this.dan2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane3 {
            get {
                return this.zakl_dane3Field;
            }
            set {
                this.zakl_dane3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane3Specified {
            get {
                return this.zakl_dane3FieldSpecified;
            }
            set {
                this.zakl_dane3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan3 {
            get {
                return this.dan3Field;
            }
            set {
                this.dan3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan3Specified {
            get {
                return this.dan3FieldSpecified;
            }
            set {
                this.dan3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kod_rezim_pl {
            get {
                return this.kod_rezim_plField;
            }
            set {
                this.kod_rezim_plField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zdph_44 {
            get {
                return this.zdph_44Field;
            }
            set {
                this.zdph_44Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1VetaA5 {
        
        private decimal zakl_dane1Field;
        
        private bool zakl_dane1FieldSpecified;
        
        private decimal dan1Field;
        
        private bool dan1FieldSpecified;
        
        private decimal zakl_dane2Field;
        
        private bool zakl_dane2FieldSpecified;
        
        private decimal dan2Field;
        
        private bool dan2FieldSpecified;
        
        private decimal zakl_dane3Field;
        
        private bool zakl_dane3FieldSpecified;
        
        private decimal dan3Field;
        
        private bool dan3FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane1 {
            get {
                return this.zakl_dane1Field;
            }
            set {
                this.zakl_dane1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane1Specified {
            get {
                return this.zakl_dane1FieldSpecified;
            }
            set {
                this.zakl_dane1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan1 {
            get {
                return this.dan1Field;
            }
            set {
                this.dan1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan1Specified {
            get {
                return this.dan1FieldSpecified;
            }
            set {
                this.dan1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane2 {
            get {
                return this.zakl_dane2Field;
            }
            set {
                this.zakl_dane2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane2Specified {
            get {
                return this.zakl_dane2FieldSpecified;
            }
            set {
                this.zakl_dane2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan2 {
            get {
                return this.dan2Field;
            }
            set {
                this.dan2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan2Specified {
            get {
                return this.dan2FieldSpecified;
            }
            set {
                this.dan2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane3 {
            get {
                return this.zakl_dane3Field;
            }
            set {
                this.zakl_dane3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane3Specified {
            get {
                return this.zakl_dane3FieldSpecified;
            }
            set {
                this.zakl_dane3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan3 {
            get {
                return this.dan3Field;
            }
            set {
                this.dan3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan3Specified {
            get {
                return this.dan3FieldSpecified;
            }
            set {
                this.dan3FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1VetaB1 {
        
        private decimal c_radkuField;
        
        private bool c_radkuFieldSpecified;
        
        private string dic_dodField;
        
        private string c_evid_ddField;
        
        private string duzpField;
        
        private decimal zakl_dane1Field;
        
        private bool zakl_dane1FieldSpecified;
        
        private decimal dan1Field;
        
        private bool dan1FieldSpecified;
        
        private decimal zakl_dane2Field;
        
        private bool zakl_dane2FieldSpecified;
        
        private decimal dan2Field;
        
        private bool dan2FieldSpecified;
        
        private decimal zakl_dane3Field;
        
        private bool zakl_dane3FieldSpecified;
        
        private decimal dan3Field;
        
        private bool dan3FieldSpecified;
        
        private string kod_pred_plField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_radku {
            get {
                return this.c_radkuField;
            }
            set {
                this.c_radkuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c_radkuSpecified {
            get {
                return this.c_radkuFieldSpecified;
            }
            set {
                this.c_radkuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dic_dod {
            get {
                return this.dic_dodField;
            }
            set {
                this.dic_dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c_evid_dd {
            get {
                return this.c_evid_ddField;
            }
            set {
                this.c_evid_ddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duzp {
            get {
                return this.duzpField;
            }
            set {
                this.duzpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane1 {
            get {
                return this.zakl_dane1Field;
            }
            set {
                this.zakl_dane1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane1Specified {
            get {
                return this.zakl_dane1FieldSpecified;
            }
            set {
                this.zakl_dane1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan1 {
            get {
                return this.dan1Field;
            }
            set {
                this.dan1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan1Specified {
            get {
                return this.dan1FieldSpecified;
            }
            set {
                this.dan1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane2 {
            get {
                return this.zakl_dane2Field;
            }
            set {
                this.zakl_dane2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane2Specified {
            get {
                return this.zakl_dane2FieldSpecified;
            }
            set {
                this.zakl_dane2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan2 {
            get {
                return this.dan2Field;
            }
            set {
                this.dan2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan2Specified {
            get {
                return this.dan2FieldSpecified;
            }
            set {
                this.dan2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane3 {
            get {
                return this.zakl_dane3Field;
            }
            set {
                this.zakl_dane3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane3Specified {
            get {
                return this.zakl_dane3FieldSpecified;
            }
            set {
                this.zakl_dane3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan3 {
            get {
                return this.dan3Field;
            }
            set {
                this.dan3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan3Specified {
            get {
                return this.dan3FieldSpecified;
            }
            set {
                this.dan3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kod_pred_pl {
            get {
                return this.kod_pred_plField;
            }
            set {
                this.kod_pred_plField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1VetaB2 {
        
        private decimal c_radkuField;
        
        private bool c_radkuFieldSpecified;
        
        private string dic_dodField;
        
        private string c_evid_ddField;
        
        private string dppdField;
        
        private decimal zakl_dane1Field;
        
        private bool zakl_dane1FieldSpecified;
        
        private decimal dan1Field;
        
        private bool dan1FieldSpecified;
        
        private decimal zakl_dane2Field;
        
        private bool zakl_dane2FieldSpecified;
        
        private decimal dan2Field;
        
        private bool dan2FieldSpecified;
        
        private decimal zakl_dane3Field;
        
        private bool zakl_dane3FieldSpecified;
        
        private decimal dan3Field;
        
        private bool dan3FieldSpecified;
        
        private string pomerField;
        
        private string zdph_44Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal c_radku {
            get {
                return this.c_radkuField;
            }
            set {
                this.c_radkuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c_radkuSpecified {
            get {
                return this.c_radkuFieldSpecified;
            }
            set {
                this.c_radkuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dic_dod {
            get {
                return this.dic_dodField;
            }
            set {
                this.dic_dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string c_evid_dd {
            get {
                return this.c_evid_ddField;
            }
            set {
                this.c_evid_ddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dppd {
            get {
                return this.dppdField;
            }
            set {
                this.dppdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane1 {
            get {
                return this.zakl_dane1Field;
            }
            set {
                this.zakl_dane1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane1Specified {
            get {
                return this.zakl_dane1FieldSpecified;
            }
            set {
                this.zakl_dane1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan1 {
            get {
                return this.dan1Field;
            }
            set {
                this.dan1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan1Specified {
            get {
                return this.dan1FieldSpecified;
            }
            set {
                this.dan1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane2 {
            get {
                return this.zakl_dane2Field;
            }
            set {
                this.zakl_dane2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane2Specified {
            get {
                return this.zakl_dane2FieldSpecified;
            }
            set {
                this.zakl_dane2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan2 {
            get {
                return this.dan2Field;
            }
            set {
                this.dan2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan2Specified {
            get {
                return this.dan2FieldSpecified;
            }
            set {
                this.dan2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane3 {
            get {
                return this.zakl_dane3Field;
            }
            set {
                this.zakl_dane3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane3Specified {
            get {
                return this.zakl_dane3FieldSpecified;
            }
            set {
                this.zakl_dane3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan3 {
            get {
                return this.dan3Field;
            }
            set {
                this.dan3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan3Specified {
            get {
                return this.dan3FieldSpecified;
            }
            set {
                this.dan3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pomer {
            get {
                return this.pomerField;
            }
            set {
                this.pomerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zdph_44 {
            get {
                return this.zdph_44Field;
            }
            set {
                this.zdph_44Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1VetaB3 {
        
        private decimal zakl_dane1Field;
        
        private bool zakl_dane1FieldSpecified;
        
        private decimal dan1Field;
        
        private bool dan1FieldSpecified;
        
        private decimal zakl_dane2Field;
        
        private bool zakl_dane2FieldSpecified;
        
        private decimal dan2Field;
        
        private bool dan2FieldSpecified;
        
        private decimal zakl_dane3Field;
        
        private bool zakl_dane3FieldSpecified;
        
        private decimal dan3Field;
        
        private bool dan3FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane1 {
            get {
                return this.zakl_dane1Field;
            }
            set {
                this.zakl_dane1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane1Specified {
            get {
                return this.zakl_dane1FieldSpecified;
            }
            set {
                this.zakl_dane1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan1 {
            get {
                return this.dan1Field;
            }
            set {
                this.dan1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan1Specified {
            get {
                return this.dan1FieldSpecified;
            }
            set {
                this.dan1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane2 {
            get {
                return this.zakl_dane2Field;
            }
            set {
                this.zakl_dane2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane2Specified {
            get {
                return this.zakl_dane2FieldSpecified;
            }
            set {
                this.zakl_dane2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan2 {
            get {
                return this.dan2Field;
            }
            set {
                this.dan2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan2Specified {
            get {
                return this.dan2FieldSpecified;
            }
            set {
                this.dan2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dane3 {
            get {
                return this.zakl_dane3Field;
            }
            set {
                this.zakl_dane3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dane3Specified {
            get {
                return this.zakl_dane3FieldSpecified;
            }
            set {
                this.zakl_dane3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan3 {
            get {
                return this.dan3Field;
            }
            set {
                this.dan3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan3Specified {
            get {
                return this.dan3FieldSpecified;
            }
            set {
                this.dan3FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostDPHKH1VetaC {
        
        private decimal obrat23Field;
        
        private bool obrat23FieldSpecified;
        
        private decimal obrat5Field;
        
        private bool obrat5FieldSpecified;
        
        private decimal pln23Field;
        
        private bool pln23FieldSpecified;
        
        private decimal pln5Field;
        
        private bool pln5FieldSpecified;
        
        private decimal pln_rez_prenField;
        
        private bool pln_rez_prenFieldSpecified;
        
        private decimal rez_pren23Field;
        
        private bool rez_pren23FieldSpecified;
        
        private decimal rez_pren5Field;
        
        private bool rez_pren5FieldSpecified;
        
        private decimal celk_zd_a2Field;
        
        private bool celk_zd_a2FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal obrat23 {
            get {
                return this.obrat23Field;
            }
            set {
                this.obrat23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool obrat23Specified {
            get {
                return this.obrat23FieldSpecified;
            }
            set {
                this.obrat23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal obrat5 {
            get {
                return this.obrat5Field;
            }
            set {
                this.obrat5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool obrat5Specified {
            get {
                return this.obrat5FieldSpecified;
            }
            set {
                this.obrat5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pln23 {
            get {
                return this.pln23Field;
            }
            set {
                this.pln23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pln23Specified {
            get {
                return this.pln23FieldSpecified;
            }
            set {
                this.pln23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pln5 {
            get {
                return this.pln5Field;
            }
            set {
                this.pln5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pln5Specified {
            get {
                return this.pln5FieldSpecified;
            }
            set {
                this.pln5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pln_rez_pren {
            get {
                return this.pln_rez_prenField;
            }
            set {
                this.pln_rez_prenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pln_rez_prenSpecified {
            get {
                return this.pln_rez_prenFieldSpecified;
            }
            set {
                this.pln_rez_prenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal rez_pren23 {
            get {
                return this.rez_pren23Field;
            }
            set {
                this.rez_pren23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rez_pren23Specified {
            get {
                return this.rez_pren23FieldSpecified;
            }
            set {
                this.rez_pren23FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal rez_pren5 {
            get {
                return this.rez_pren5Field;
            }
            set {
                this.rez_pren5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rez_pren5Specified {
            get {
                return this.rez_pren5FieldSpecified;
            }
            set {
                this.rez_pren5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal celk_zd_a2 {
            get {
                return this.celk_zd_a2Field;
            }
            set {
                this.celk_zd_a2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool celk_zd_a2Specified {
            get {
                return this.celk_zd_a2FieldSpecified;
            }
            set {
                this.celk_zd_a2FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PisemnostKontrola {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
}
